definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.TaskRequest:
    properties:
      scan_type:
        enum:
        - full
        - quick
        type: string
      target_url:
        type: string
    required:
    - scan_type
    - target_url
    type: object
  dto.TaskResponse:
    properties:
      id:
        type: string
      status:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks:
    post:
      consumes:
      - application/json
      description: 接收任务参数并生成唯一任务ID
      parameters:
      - description: 任务参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.TaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.TaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 创建扫描任务
      tags:
      - Tasks
swagger: "2.0"
